### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [nikos912000/octree-partitioning#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by nikos912000** [comment]
Hi there!

This is a pretty old uni project and didn't add a license to it when I created it.
Happy to add one now. How are you planning to use it?

**Comment by suprafun** [comment]
Just to learn C++ and multithreading in the context of spatial partitioning. Your project seems to be well commented and compact, so a great learning resource.

**Comment by nikos912000** [comment]
Cool, license added :)
